name: Deploy to Heroku

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment for building the frontend (React)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify the Node.js version for React

    # Step 3: Install frontend dependencies and build
    - name: Install dependencies and build React app
      working-directory: ./houseing/src/compo/homePage # Specify the React app folder
      run: |
        npm install
        npm run build

    # Step 4: Setup Python for the Flask backend
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version

    # Step 5: Install backend dependencies (Flask, etc.)
    - name: Install backend dependencies
      working-directory: ./housing/flask_api.py  # Specify the Flask app folder
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 6: Login to Heroku using the Heroku API key
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Set the API key as a secret in GitHub
      run: |
        echo $HEROKU_API_KEY | heroku auth:token

    # Step 7: Deploy to Heroku
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/your-heroku-app-name.git
        git push heroku main  # Push to Heroku main or your target branch

# 5446 7001 0073 6293
# 09 / 26
# 949