name: Deploy to Heroku

on:
  push:
    branches:
      - main  # The branch to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment for building the frontend (React)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use Node.js version 20

    # Step 3: Install frontend dependencies and build
    - name: Install dependencies and build React app
      working-directory: ./houseing  # Ensure the correct React app folder
      run: |
        npm install
        npm run build

    # Step 4: Set up Python environment for the Flask backend
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 5: Install backend dependencies (Flask, etc.)
    - name: Install backend dependencies
      working-directory: ./  # Ensure you are in the correct working directory
      run: |
        python -m venv venv  # Create the virtual environment inside the current directory
        source ./venv/bin/activate  # Activate the virtual environment
        pip install -r requirements.txt  # Install required dependencies

    # Step 6: Login to Heroku using the Heroku API key
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Set the API key as a secret in GitHub
      run: |
        echo $HEROKU_API_KEY | heroku auth:token

    # Step 7: Deploy to Heroku
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/your-heroku-app-name.git
        git push heroku main  # Push to Heroku main or your target branch
